### ISSUE TITLE
Hex color values

### ISSUE THREAD

**Issue by pushred** [postcss/postcss-color-function#11]
Is there any particular reason that hex values aren't supported currently? I'm trying to work from a base palette defined as variables but they were defined in hex as the designer specified them. Seems like this should work but I get:

`Unable to parse color from string "#ffffff,"`

I suppose it's just an issue with the spec, it's odd how they provide the results in their examples as hex. But only rgb/hsl/hwb for input?

**Comment by TrySound** [comment]
@pushred Read documentation, please. You shoudn't use comma after hex.

**Comment by pushred** [comment]
Ahhh, must have been that Sass habit. Thanks!
