### ISSUE TITLE
Lighten support

### ISSUE THREAD

**Issue by nicotsou** [postcss/postcss-color-function#18]
Good evening guys,

Is there any plan to include the lighten() functionality? Maybe any workaround to make it happen?

**Comment by MoOx** [comment]
Is this part of the css spec now?

**Comment by nicotsou** [comment]
I'm not sure it is. I know it from SASS.

**Comment by nicotsou** [comment]
I just found I can use l(+5%) to accomplish the same functionality. This is what I was looking for...
