### ISSUE TITLE
support for currentcolor

### ISSUE THREAD

**Issue by lionelB** [postcss/postcss-color-function#2]
It would be nice to support `color(currentcolor color-adjuster())` 

by  the way, thx for this project !

**Comment by MoOx** [comment]
It's impossible since this will require computation on runtime.
`currentcolor` depends on the cascade.
I will add a note in the README.

**Comment by lionelB** [comment]
thx.
I guess this apply also to the #3

**Comment by stevenvachon** [comment]
Could it not walk up the CSSOM to find a color definition? If none is found, default to black. I understand that this is not specification-compliant, but neither is this library's implementation of `var()`.

**Comment by MoOx** [comment]
It just can't. We don't have the DOM and only the DOM say the truth.

**Comment by stevenvachon** [comment]
We don't necessarily need the truth when we're compiling.

**Comment by MoOx** [comment]
For the exact same reason postcss-custom-properties is limited to root, I will never this kind of stuff.

**Comment by stevenvachon** [comment]
Alright, fair enough.
