### ISSUE TITLE
blend() parsing error for rgb colors

### ISSUE THREAD

**Issue by ccheney** [postcss/postcss-color-function#29]
Input:

```
background-color: color(rgb(1,1,1) blend(red 50%));
```

Output:

```
background-color: rgb(128, 1, 1);
```

---

Input:

```
background-color: color(rgb(1,1,1) blend(rgb(2,2,2) 50%));
```

Output:

> Error: <css input>:2:3: Unable to parse color from string "rgb(2,2,2"

**Comment by MoOx** [comment]
Can you report this issue here https://github.com/ianstormtaylor/css-color-function ?

**Comment by ccheney** [comment]
https://github.com/ianstormtaylor/css-color-function/issues/23
