### ISSUE TITLE
color() and rgba() function syntax spec changes 

### ISSUE THREAD

**Issue by kevinSuttle** [postcss/postcss-color-function#31]
http://www.xanthir.com/b4iW0

**Comment by Semigradsky** [comment]
Syntax changed in another functions too: https://wiki.csswg.org/ideas/functional-notation
Maybe it would be better to make in a separate plugin. Not in `postcss-color-function`

**Comment by MoOx** [comment]
This has been done already, see https://github.com/MoOx/postcss-cssnext/commit/e2ae3b3c0f282a099fc2606b0655b2716cc0721e
