### ISSUE TITLE
Function is `color-mod()` not `color()`

### ISSUE THREAD

**Issue by jonathantneal** [postcss/postcss-color-function#43]
> cssnext is out of date when it comes to color()

https://twitter.com/evaferreira92/status/905104662709272576

It seems, at a high level, the method name has changed from `color()` to `color-mod()`.

**Comment by jonathantneal** [comment]
This may be resolved by the outcome of this discussion: https://github.com/ianstormtaylor/css-color-function/issues/29#issuecomment-335518678

**Comment by jonathantneal** [comment]
That discussion was not resolved, but all ambiguity over the name was cleared up in the working draft: https://drafts.csswg.org/css-color-4/#modifying-colors

**Comment by kumarharsh** [comment]
So, would this end up being changed to `color-mod()` in this library too?

**Comment by jhpratt** [comment]
@jonathantneal Any plans to alias it and deprecate `color()`?

**Comment by jonathantneal** [comment]
No, I went with the standard, and have used that name for some time.
