### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by lersh** [postcss/postcss-color-function#45]
Platform:Raspberry Pi 2B
OS:Raspbian 
NodeJs:v6.11.3
npm:3.10.10
I follow the Usage,installed postcss-color-function,and create index.js
run node index.js
Nothing happened,input.css does not change

**Comment by TrySound** [comment]
Your issue is not informative without your configs.

**Comment by Semigradsky** [comment]
@lersh ping

**Comment by lersh** [comment]
sorry，I gave up to use it
