### ISSUE TITLE
Sass::color::mix support

### ISSUE THREAD

**Issue by iamstarkov** [postcss/postcss-color-function#9]
Sass have very nice feature to mix colors, which have a name [mix](http://sass-lang.com/documentation/Sass/Script/Functions.html#mix-instance_method). [Example from ALA](http://alistapart.com/article/dry-ing-out-your-sass-mixins#section14).
Does postcss-color-function support it?

**Comment by MoOx** [comment]
This plugin transform W3C CSS color function. If there is no spec about that (and I don't think there is for now), this will not be supported.

**Comment by ai** [comment]
@iamstarkov it is time to start own plugin? :-)

**Comment by iamstarkov** [comment]
probably =)

**Comment by iamstarkov** [comment]
> This plugin transform W3C CSS color function. If there is no spec about that (and I don't think there is for now), this will not be supported.

Can you state this in readme and include link to this spec too?

**Comment by MoOx** [comment]
The readme already mention that it is transforming W3C CSS color function.
I will add link to spec

**Comment by iamstarkov** [comment]
thanks a lot =)
